name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build docs
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install && build
      run: |
        npm install
        npm run build
        
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: $GITHUB_TOKEN
        # Destination branch to push changes
        branch: docs
        # Determines if force push is used
        force: true
        # Directory to change to before pushing.
        directory: dist
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
