name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build docs
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install && build
      run: |
        npm install
        npm run build
        
        rm -rf docs
        mkdir docs
        cp -rf dist/* docs
        rm -rf dist
        
        git config --global user.email "735267452@qq.com"
        git config --global user.name "AJLoveChina"
    
        git show-ref
        
        git add .
        git commit -m "update docs by Github Actions"
        git remote set-url --push origin https://AJLoveChina:$GITHUB_TOKEN@github.com/AJLoveChina/awesome-qrcode
        git remote -v
        git checkout -b master
        git push origin HEAD:master --force
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
