name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build docs
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: actions/setup-python@v1
      with:
        python-version: '2.x'
        architecture: 'x64'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        rm -rf docs
        mkdir docs
        cp dist/* docs/*
        git add docs/
        git commit -m "update docs by Github Actions"
        git push origin master
      env:
        CI: true
